name: Find and Repalce and Recommit
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: ".fastandstatic.com/"
          replace: "/"
          regex: false
      - name: Simple commit
  # You may pin to the exact commit or the version.
  # uses: zwaldowski/git-commit-action@66730766679672410dc04830ae6389f4376c8c94
  uses: zwaldowski/git-commit-action@v1
  with:
    # Directory to create commit in
    working_directory: /page
    # Commit message
    commit_message: # default is Automated commit
    # Name to use for commit author
    author_name: # optional, default is GitHub Actions
    # Email to use for commit author
    author_email: # optional, default is actions@github.com
